import { CategoryInfo, StoreSettings } from '@/types';

export const STORE_INFO = {
  name: 'Alvin Swalayan',
  tagline: 'Hemat & Berkualitas',
  headline: 'Belanja Kebutuhan Harian Lebih Mudah',
  subheadline: 'Pesan kebutuhan rumah tangga dari Alvin Swalayan, langsung diantar ke tempat Anda di Banda Aceh.',
  ctaText: 'Belanja Sekarang',
  address: 'Jl. AMD No.1, RW.2, Peunyeurat, Kec. Banda Raya, Kota Banda Aceh, Aceh 23117',
  areaCoverage: 'Banda Aceh & Sekitarnya (Kec. Banda Raya, Baiturrahman, Kuta Alam, Lueng Bata, Syiah Kuala, Ulee Kareng, Meuraxa, Jaya Baru)',
  phone: '0812-6900-8899',
  whatsapp: '6281269008899',
  whatsappUrl: 'https://wa.me/6281269008899',
  email: 'alvinswalayan.aceh@gmail.com',
  googleMapsUrl: 'https://maps.app.goo.gl/kwiWMrHHG4S5V3GMA',
  googleMapsEmbedUrl: 'https://maps.google.com/maps?q=5.5322362,95.3273363&hl=id&z=17&output=embed',
  operatingHours: 'Setiap Hari: 07.30 - 22.30 WIB',
  instagram: '@alvinswalayan.aceh',
  deliveryFeeFlat: 10000,
  freeDeliveryThreshold: 150000,
  bankAccounts: [
    {
      bank: 'Bank Syariah Indonesia (BSI)',
      accountNumber: '7123-8899-001',
      accountName: 'ALVIN SWALAYAN BANDA ACEH',
    },
    {
      bank: 'Bank Aceh Syariah (BAS)',
      accountNumber: '010-02-40-008899-1',
      accountName: 'ALVIN SWALAYAN',
    }
  ],
};

export const DEFAULT_STORE_SETTINGS: StoreSettings = {
  store_name: STORE_INFO.name,
  store_phone: STORE_INFO.phone,
  store_email: STORE_INFO.email,
  store_address: STORE_INFO.address,
  shipping_fee: STORE_INFO.deliveryFeeFlat,
  free_delivery_threshold: STORE_INFO.freeDeliveryThreshold,
  bank_name: 'Bank Syariah Indonesia (BSI)',
  bank_account_number: '7123-8899-001',
  bank_account_name: 'ALVIN SWALAYAN BANDA ACEH',
  secondary_bank_name: 'Bank Aceh Syariah (BAS)',
  secondary_bank_account_number: '010-02-40-008899-1',
  secondary_bank_account_name: 'ALVIN SWALAYAN',
  cod_enabled: true,
  cod_max_amount: 200000,
  bank_transfer_enabled: true,
  midtrans_enabled: true,
  midtrans_client_key: process.env.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY || '',
  midtrans_server_key: process.env.MIDTRANS_SERVER_KEY || '',
  midtrans_is_production: false,
  maintenance_mode: false,
  fonnte_token: process.env.NEXT_PUBLIC_FONNTE_TOKEN || '',
};

// 14 Official Categories as mandated by Master Prompt Section 5
export const CATEGORIES: CategoryInfo[] = [
  {
    id: 'sembako',
    name: 'Sembako',
    slug: 'sembako',
    iconName: 'Wheat',
    description: 'Beras, minyak goreng, gula, tepung, telur, dan bumbu dapur pokok',
    is_active: true,
    sort_order: 1,
  },
  {
    id: 'minuman',
    name: 'Minuman',
    slug: 'minuman',
    iconName: 'Coffee',
    description: 'Kopi Aceh, teh, air mineral, susu, sirup, dan jus segar',
    is_active: true,
    sort_order: 2,
  },
  {
    id: 'makanan',
    name: 'Mie & Makanan Instan',
    slug: 'makanan',
    iconName: 'Utensils',
    description: 'Mi instan, sarden, kornet, kecap, saus, dan makanan siap saji',
    is_active: true,
    sort_order: 3,
  },
  {
    id: 'snack',
    name: 'Snack & Biskuit',
    slug: 'snack',
    iconName: 'Cookie',
    description: 'Keripik, biskuit, cokelat, permen, dan camilan keluarga',
    is_active: true,
    sort_order: 4,
  },
  {
    id: 'susu-sarapan',
    name: 'Susu & Breakfast',
    slug: 'susu-sarapan',
    iconName: 'CupSoda',
    description: 'Susu UHT, krimer, sereal, havermut, selai, dan kopi sachet',
    is_active: true,
    sort_order: 5,
  },
  {
    id: 'bumbu-masak',
    name: 'Bumbu & Bahan Masak',
    slug: 'bumbu-masak',
    iconName: 'Flame',
    description: 'Kecap, saus tiram, penyedap rasa, garam, santan, dan minyak wijen',
    is_active: true,
    sort_order: 6,
  },
  {
    id: 'personal-care',
    name: 'Perawatan Diri',
    slug: 'personal-care',
    iconName: 'Sparkles',
    description: 'Sabun mandi, sampo, pasta gigi, sikat gigi, deodorant, dan perawatan kulit',
    is_active: true,
    sort_order: 7,
  },
  {
    id: 'rumah-tangga',
    name: 'Rumah Tangga',
    slug: 'rumah-tangga',
    iconName: 'Home',
    description: 'Deterjen, sabun cuci piring, pembersih lantai, pewangi pakaian, dan tissue',
    is_active: true,
    sort_order: 8,
  },
  {
    id: 'bayi-anak',
    name: 'Bayi & Anak',
    slug: 'bayi-anak',
    iconName: 'Baby',
    description: 'Popok bayi, susu formula anak, bubur bayi, minyak telon, dan lotion',
    is_active: true,
    sort_order: 9,
  },
  {
    id: 'sekolah',
    name: 'Kebutuhan Sekolah',
    slug: 'sekolah',
    iconName: 'BookOpen',
    description: 'Buku tulis, pulpen, pensil, penghapus, penggaris, dan alat tulis kantor',
    is_active: true,
    sort_order: 10,
  },
  {
    id: 'produk-segar',
    name: 'Produk Segar',
    slug: 'produk-segar',
    iconName: 'Apple',
    description: 'Buah-buahan pilihan, sayuran segar harian, bawang, dan bumbu basah',
    is_active: true,
    sort_order: 11,
  },
  {
    id: 'frozen-food',
    name: 'Frozen Food',
    slug: 'frozen-food',
    iconName: 'Snowflake',
    description: 'Nugget, sosis, bakso, kentang beku, dan olahan beku siap masak',
    is_active: true,
    sort_order: 12,
  },
  {
    id: 'kesehatan',
    name: 'Kesehatan & P3K',
    slug: 'kesehatan',
    iconName: 'HeartPulse',
    description: 'Minyak kayu putih, tolak angin, plester, vitamin C, dan obat bebas',
    is_active: true,
    sort_order: 13,
  },
  {
    id: 'pet-care',
    name: 'Pet Care',
    slug: 'pet-care',
    iconName: 'PawPrint',
    description: 'Makanan kucing, pasir kucing, snack hewan peliharaan, dan sampo',
    is_active: true,
    sort_order: 14,
  },
];

export const STORE_BENEFITS = [
  {
    title: 'Produk Kebutuhan Harian Lengkap',
    description: 'Mulai dari beras, minyak, bumbu dapur, hingga perlengkapan mandi tersedia lengkap di toko kami.',
    icon: 'CheckCircle2',
  },
  {
    title: 'Harga Bersaing & Hemat',
    description: 'Harga jujur dan terjangkau setiap hari untuk warga Kota Banda Aceh dan sekitarnya.',
    icon: 'Tag',
  },
  {
    title: 'Pengantaran Cepat Banda Aceh',
    description: 'Pesanan diantar langsung oleh armada kurir toko kami ke depan pintu rumah Anda.',
    icon: 'Truck',
  },
  {
    title: 'Bisa Bayar di Tempat (COD)',
    description: 'Belanja tenang dan nyaman. Bayar tunai setelah pesanan tiba di rumah Anda.',
    icon: 'ShieldCheck',
  },
];
